version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5001:8000"
    depends_on:
      - db
